# Name your project! 
name: 'adventure_works_analytics'
version: '1.0.0'
config-version: 2

# Ajustado para conectar com o nome correto do seu arquivo profiles.yml
profile: 'adventure_works_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  adventure_works_analytics:
    # Removemos as linhas "+schema" para que todas as views e tabelas 
    # caiam direto dentro do seu schema 'dbt_adventure_works', exatamente como o do professor.
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table